// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MeuBolsoBackend;
[DbContext(typeof(AppDbContext))]
[Migration("20241009212743_AddTag")]
partial class AddTag
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("MeuBolso.Api.Entities.TagEntity", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<string>("Cor")
                    .HasMaxLength(7)
                    .HasColumnType("character varying(7)");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<long>("UsuarioId")
                    .HasColumnType("bigint");

                b.HasKey("Id");

                b.HasIndex("UsuarioId");

                b.ToTable("Tags");
            });

        modelBuilder.Entity("MeuBolso.Api.Entities.UsuarioEntity", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<decimal?>("Renda")
                    .HasColumnType("numeric");

                b.Property<string>("Sobrenome")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("Usuarios");
            });

        modelBuilder.Entity("MeuBolso.Api.Entities.TagEntity", b =>
            {
                b.HasOne("MeuBolso.Api.Entities.UsuarioEntity", null)
                    .WithMany()
                    .HasForeignKey("UsuarioId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
    }
}
